### ISSUE TITLE
mod a ajoutée 

### ISSUE THREAD

**Issue by Jehenn** [El-Taberna/Taberna-Modpack-6#10]
ore excavation mais avec des restrictions couper que les arbres et pas les minerais ou l'inverse 
https://www.curseforge.com/minecraft/mc-mods/ore-excavation/files

Merci bien bissous

**Comment by ElBrigos** [comment]
thhis mod is stable, i do more test on launcher and terraforged mod to check compatibility, thanks for your share

**Comment by ElBrigos** [comment]
mod refuse create lag with terraforged
