### ISSUE TITLE
Mod Manquant

### ISSUE THREAD

**Issue by YameteeiiatneH** [El-Taberna/Taberna-Modpack-6#2]
Bonsoir Monsieur,
Je soussignée, Jade XX, vous informes avec politesse et sagesse qu'il manque le mod JEI sur votre serveur auquel elle aime jouer malgré une petite larme versée hier dû à sa mort hier et sa perte de STUFF.

Merci de votre compréhension et de rajouter ce mod afin de faciliter la vie de vos joueurs fidèle.

Cordialement.

**Comment by ElBrigos** [comment]
Add Just Enought Item on Taberna 6 Official Server

Thx for the report, he will be patch in few hours.

**Comment by ElBrigos** [comment]
Problem Fix, thanks for the report !
