### ISSUE TITLE
Rajout de mod

### ISSUE THREAD

**Issue by Jehenn** [El-Taberna/Taberna-Modpack-6#3]
Bonjour monsieur est ce que sa serai possible de rajouté le mod
Fast furnace ou bien more furnace 

Cordialement Jehenn

**Comment by ElBrigos** [comment]
I go to check the source on github. I'll keep you informed

**Comment by ElBrigos** [comment]
More furnace is deprecated,
I check fast furnace

**Comment by ElBrigos** [comment]
Mod Refuse
