### ISSUE TITLE
Pluging a ajouté

### ISSUE THREAD

**Issue by YameteeiiatneH** [El-Taberna/Taberna-Modpack-6#4]
Rebonsoir monsieur, 

Je re-soussignée Jade XX, vous fait part d'une idée de pluging à mettre sur votre serveur afin d'éviter les LAGS : 

Clean Items

cordialement

**Comment by ElBrigos** [comment]
We can't add plugin, because the support of forge and bukkit or sponge was stopped in 1.12.2
