### ISSUE TITLE
Mod a rajoutée 

### ISSUE THREAD

**Issue by Jehenn** [El-Taberna/Taberna-Modpack-6#6]
Mouse tweaks: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files

waystones: https://www.curseforge.com/minecraft/mc-mods/waystones/files

**Comment by ElBrigos** [comment]
Way Stone refused because teleporter is not roleplay.

**Comment by ElBrigos** [comment]
second mod refuse
