### ISSUE TITLE
 Bug present on the server

### ISSUE THREAD

**Issue by YameteeiiatneH** [El-Taberna/Taberna-Modpack-6#8]
Hello,

I told you about a problem on the server.
When I choose a resource pack and restart my game, the choice was reset and I cannot add a resource pack because it gets deleted all the time. It's the same with Shaders.

Cordially

**Comment by ElBrigos** [comment]
If you try to use your own ressource pack is normal, because you try to add an external file of the launcher.
Have you the same issues with the ressource pack included in the ModPack ?

**Comment by YameteeiiatneH** [comment]
Yes I have the same problem with your resource pack

**Comment by ElBrigos** [comment]
have you make an other modification ?

**Comment by YameteeiiatneH** [comment]
No, I just tried to put a resourcepack that I like and a shader suitable for my PC

**Comment by ElBrigos** [comment]
if you add an other files the launcher try to remove that files, don't put an other files in the launcher directory and retry
