### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sukya14** [El-Taberna/Taberna-Modpack-6#9]
J'ai freeze quand je suis rentré sur le serv environ 5 sec plus tard ensuite je clique sur le jeu puis il plante et me demande si je veut forcer l'arrêt du jeu. Ram alloué 5Go 
[latest.log](https://github.com/El-Taberna/Taberna-Modpack-6/files/5951717/latest.log)

**Comment by ElBrigos** [comment]
Can i have a screen to this message when he ask you ?

**Comment by Sukya14** [comment]
![16128846330198789872447090856454](https://user-images.githubusercontent.com/78803204/107386568-42c98680-6af4-11eb-90a5-150dd210fc05.jpg)
![Uploading 1612884694931295194314445697954.jpg…]()

**Comment by ElBrigos** [comment]
_All solution has been tested the problem is not Taberna 6, this is the computer comportment with Forge i can't make support for that sorry_
